[package]
name = "s-cybersage-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.94.1"

[dependencies]
anyhow = "1.0.99"
athenaeum = { git = "https://github.com/JarredTD/Athenaeum.git", tag = "v0.1.1", features = ["http"] }
aws-config = { version = "1.8.6", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { version = "1.93.0", default-features = false, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
aws-sdk-secretsmanager = { version = "1.88.0", default-features = false, features = ["behavior-version-latest", "default-https-client", "rt-tokio"] }
lambda_http = "0.17.0"
lambda_runtime = { version = "0.14.4", features = ["anyhow"] }
reqwest = { version = "0.12.23", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.225", features = ["serde_derive"] }
serde_json = "1.0.145"

tokio = { version = "1", features = ["macros", "rt"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[dev-dependencies]
wiremock = "0.6.5"
